In [2]:
import numpy as np

nums = np.array([10, 20, 30, 40, 50])


In [5]:
# 브로드 캐스팅 - +, -, *, /, **
nums2 = nums ** 2
nums3 = nums / 10
print(nums)
print(nums2)
print(nums3)

[10 20 30 40 50]
[ 100  400  900 1600 2500]
[1. 2. 3. 4. 5.]


In [8]:
nums = np.array([[1, 10], [2, 20], [3, 30], [4, 40]])
# print(nums)

nums2 = nums[:,0]
print(nums2)

nums3 = nums[:,1]
print(nums3)

[1 2 3 4]
[10 20 30 40]


In [10]:
# 차원 수 변경 - reshape
nums = np.array([1, 2, 3, 4, 5, 6])
print(nums)

nums2 = nums.reshape(3, 2) # 3행 2열
print(nums2)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [12]:
# 넘파이 인덱싱 
nums = np.array([10, 20, 30, 40, 50, 60, 70])
print(nums)

nums2 = nums[[1,3,5]] # 1, 3, 5 항목 추출 
print(nums2)

[10 20 30 40 50 60 70]
[20 40 60]


In [14]:
# arange(숫자) 0 ~ 숫자 
print(np.arange(10)) # 0~9

# arange(시작, 종료) 시작 번호 ~ 종료 번호 미만 
print(np.arange(10, 20))

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [18]:
# random.shuffle : 넘파이 배열을 무작위로 섞어줄때 
nums = np.arange(10)
np.random.shuffle(nums)
print(nums)

[2 5 3 7 8 1 4 9 6 0]
