In [1]:
import numpy as np

nums = np.array([88, 67, 90, 100])
print(np.mean(nums))

86.25


In [5]:

nums = np.array([
        [88, 67, 90, 100],
        [44, 70, 80, 90],
        [70, 55, 89, 100]
    ])

# 행별로 평균 구하기
print(np.mean(nums, axis=1)) # axis - 0 : 열별 평균, 1 - 행별 평균

# 열별로 평균 구하기
print(np.round(np.mean(nums, axis=0), decimals=2))

# 행별로 표준편차 구하기
print(np.std(nums, axis=1))

# 열별로 표준편차 구하기 
print(np.std(nums, axis=0))

[86.25 71.   78.5 ]
[67.33 64.   86.33 96.67]
[12.00780996 17.11724277 17.29884389]
[18.06162291  6.4807407   4.49691252  4.71404521]
